### PR TITLE
Adding Switch connection view for dell 14g servers

### PR DESCRIPTION
**Pull request by keedya**
depends on: 
- https://github.com/RackHD/smi-lib-wsman/pull/17
- https://github.com/RackHD/smi-lib-adapter-server/pull/22

### CODE REVIEW

**Comment by keedya** [comment]
tagging @michaelsteven @phelpdh  for reviews

**Review by michaelsteven — DISMISSED** [review]
looks good

**Review by phelpdh — APPROVED** [review]
Looks good

**Comment by michaelsteven** [comment]
@keedya, please edit the build.gradle and set com.dell.isg.smi:adapter-server:1.0.81
Thanks!

**Comment by keedya** [comment]
@michaelsteven all set

**Review by michaelsteven — APPROVED** [review]

**Pull request merged**
